### PR TITLE
fix(lint): underscore prefixed file names should be resolved before linting

### PR DESCRIPTION
**Pull request by pevisscher**

### CODE REVIEW

**Comment by pevisscher** [comment]
Current dependencies on/for this PR:
* main
  * **PR #69** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/69" target="_blank">Graphite</a> 
    * **PR #70** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/70" target="_blank">Graphite</a> 
      * **PR #72** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/72" target="_blank">Graphite</a> 
      * **PR #71** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/71" target="_blank">Graphite</a> 
        * **PR #73** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/73" target="_blank">Graphite</a> 
          * **PR #74** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/74" target="_blank">Graphite</a>  👈
            * **PR #75** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/75" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/node-standards/74?utm_source=stack-comment).

**Comment by pevisscher** [comment]
Current dependencies on/for this PR:
* main
  * **PR #69** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/69" target="_blank">Graphite</a> 
    * **PR #70** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/70" target="_blank">Graphite</a> 
      * **PR #72** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/72" target="_blank">Graphite</a> 
      * **PR #71** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/71" target="_blank">Graphite</a> 
        * **PR #73** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/73" target="_blank">Graphite</a> 
          * **PR #74** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/74" target="_blank">Graphite</a>  👈
            * **PR #75** <a href="https://app.graphite.dev/github/pr/skyleague/node-standards/75" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/skyleague/node-standards/74?utm_source=stack-comment).

**Review by MickVanDuijn — APPROVED** [review]

**Comment by pevisscher** [comment]
@pevisscher queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/skyleague/node-standards/74).

**Comment by pevisscher** [comment]
@pevisscher merged this pull request with [Graphite](https://app.graphite.dev/github/pr/skyleague/node-standards/74).

**Pull request merged**
